<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Magenerds
 * @package    Magenerds_CountryPopUp
 * @subpackage view
 * @copyright  Copyright (c) 2018 TechDivision GmbH (http://www.techdivision.com)
 * @link       http://www.techdivision.com/
 * @author     Philipp Steinkopff <p.steinkopff@techdivision.com>
 */

$hintedCountry = $this->hintedCountry();

?>
<div data-mage-init='{
    "countryModal":{
        "hinted_country":   "<?php echo var_export($hintedCountry['hinted'], true); ?>",
        "cookie_lifetime":  "<?php echo $this->getCookieDuration(); ?>"
    }
}' id="language-modal" style="display:none;">
    <?php if($this->getModalImage()): ?>
        <div class="img-wrapper">
            <img src="<?php echo $this->getModalImage(); ?>" />
        </div>
    <?php endif; ?>
    <div class="content clearfix">
        <?php echo $this->getModalText($hintedCountry['locale']); ?>
    </div>
</div>